[package]
name = "example"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
themer = {path = "../../crates/themer"}
stylist = { version = "0.11.0", features = [ "yew_integration"] }
yew = { version = "0.20.0", features = ["csr"] }
once_cell = "1.15.0"