[workspace]
members = [
    "crates/themer",
    "crates/themer-core",
    "crates/themer-macros",

    "examples/minimal",
    "examples/storage",
    "examples/theme-switcher",
    "examples/use-browser-theme",
]

[profile.release]
opt-level = 'z'
lto = true
codegen-units = 1
panic = "abort"