[workspace]
members = [
    "crates/themer",
    "crates/themer-core",
    "crates/themer-macros",

    "examples/3_themes",
]

[profile.release]
opt-level = 'z'
lto = true
codegen-units = 1
panic = "abort"