[package]
name = "themer-macros"
version.workspace = true
license.workspace = true
edition.workspace = true
repository.workspace = true

[lib]
proc-macro = true

[dependencies]
themer-core = { path = "../themer-core" }
quote = "1.0"
syn = { version = "2.0", features = ["full", "extra-traits"] }
