[package]
name = "themer-core"
version = "0.1.0"
edition = "2021"

[dependencies]
gloo-storage = "0.2.2"
serde = { version = "1.0.151", features = ["derive"] }

[dependencies.web-sys]
version = "0.3.60"
features = [
    "Storage",
    "Window",
    "MediaQueryList",
]
