[package]
name = "example-use-browser-theme"
version.workspace = true
license.workspace = true
edition.workspace = true
repository.workspace = true

[dependencies]
themer = { path = "../.." }
yew = { version = "0.21", features = ["csr"] }
